### ISSUE TITLE
看到这个项目

### ISSUE THREAD

**Issue by 1617176084** [alwxkxk/soft-and-hard#1]
5和6是还没完成吗

**Comment by alwxkxk** [comment]
没有呢，我时间蛮紧的。
整个教程其实就是指明方向而已，大部分都是要自学的。可以看着关键字来自学。有什么问题欢迎提问。

**Comment by 1617176084** [comment]
我也处于这个过程，可以加qq吗，平时可以在工作中一起交流互助下

**Comment by alwxkxk** [comment]
readme里有Q群，638456092
